apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0        
        ports:
        - containerPort: 27017

        env:
        # "MONGO_INITDB_ROOT_USERNAME" is a env var used by mongo application
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:  # i.e. value will be from Secret
              # value from mongodb-secret.yaml > metadata > name
              name: mongodb-secret          
              # value from mongodb-secret.yaml > data > "mongo-user"    
              key: mongo-user

        # "MONGO_INITDB_ROOT_PASSWORD" is a env var used by mongo application
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef: # i.e. value will be from Secret
              # value from mongodb-secret.yaml > metadata > name 
              name: mongodb-secret
              # value from mongodb-secret.yaml > data > "mongo-password"   
              key: mongo-password           

---
# SERVICE #
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP

      # port of service
      port: 27017

      # port of container
      targetPort: 27017