apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque    
data:
  mongo-user: bW9uZ291c2Vy                # base64 encoded "mongouser"
  mongo-password: bW9uZ29wYXNzd29yZA==    # base64 encoded "mongopassword"