apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nanajanashia/k8s-demo-app:v1.0
        ports:
        - containerPort: 3000
        env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-user
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-password
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-url
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  # Set "type" = "NodePort" for external service
  # Other options: "ClusterIP" (Default) | "LoadBalancer" | "ExternalName"
  # More on type https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: NodePort

  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

      # "nodePort" needs to be added here, because type=NodeType requires it
      # it is the port that'll be exposed, externally
      # value must be between 30000 - 2767
      nodePort: 30000